apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t5ds8lugv-python 
  janus-idp.io/tekton: t5ds8lugv-python
  backstage.io/kubernetes-id: t5ds8lugv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t5ds8lugv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml